### ISSUE TITLE
Additional visualizations of collected results

### ISSUE THREAD

**Issue by critzo** [m-lab/measure-app#10]
An additional tab or set of visualizations should be provided to show the results collected by the app over time in a series of graphs or charts. This tab might be called "Analyze" and provide three charts, one each for Download Throughput, Upload Throughput and Minimum RTT, which graph the results saved by that App instance. By default the chart should show the last 10 results graphed over time in the visual style of the Observatory, with the option to change the time range being displayed.

**Comment by georgiamoon** [comment]
This relates to my comment about a different layout for more data exploration.
