### ISSUE TITLE
Make the upload feature configurable

### ISSUE THREAD

**Issue by laiyi-ohlsen** [m-lab/measure-app#109]
The measure-app extension, in addition to the already existing Settings section, will let the user enable the upload of test results to an Upload Service. If this option is enabled, the user will also be asked to provide the Upload Service URL. Optional configurable fields are BrowserID, DeviceType and Notes (e.g. Location). The extension will run a validity check on the provided URL and notify the user if such URL cannot be reached.

**Comment by robertodauria** [comment]
Closed by #119
