### ISSUE TITLE
Clarification of the "Hide" function in results history

### ISSUE THREAD

**Issue by critzo** [m-lab/measure-app#12]
For each test in the history, there is a link to "Hide" a particular test result. It's unclear why this exists and what happens when I click it. Does this remove the result from the history completely? In this case we need to say something other than "Hide", perhaps "Delete". If the result is not being deleted when this function is used, how do I restore that result if I accidentally clicked it? Should this function even be an option?

**Comment by collina** [comment]
Changed to delete.
