### ISSUE TITLE
Add configuration support for deployment through Chrome Management Console

### ISSUE THREAD

**Issue by critzo** [m-lab/measure-app#135]
The app can be deployed through the https://admin.google.com device and browser management features. However, for organizations who wish to deploy the Chrome app to many browsers to assess the connectivity of their students/employees/etc working remotely, there is a strong need to configure the app settings without requiring end-user intervention.

Researching how this might be done, I found this documentation about adding a script that runs immediately after the app is installed: https://developer.chrome.com/extensions/runtime#event-onInstalled

**Comment by critzo** [comment]
In follow up to our chat this morning, I've setup one managed Chrome browser in our domain and can force install the Chrome Extension to it. However there doesn't appear to be a way to upload an extension and deploy it. The options for adding extensions and apps are: 
* by url - point to a Progressive Web App to be installed
* by Chrome app extension or id
* android store
* chrome web store

So a PWA with a post install script or something might be the only way to do this.

**Comment by critzo** [comment]
Further update, we are unable to test managed chromebooks at this time because our Gsuite addition does not support Chrome Enterprise

**Comment by pedogski** [comment]
@critzo Thanks for the mail and heads up. I am still very much interested in the updated documentation whenever it is available. Thanks

**Comment by critzo** [comment]
@pedogski The Chrome browser extension can be deployed to managed browsers and/or devices in your GSuite organization. I would suggest you consult Google's documentation on managing browsers and/or devices for more information.
