### ISSUE TITLE
From DC on Comcast, initially mlab-ns routing to Nairobi

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/measure-app#15]

**Comment by mtlynch** [comment]
Is this an mlab-ns issue or a measure-app issue? What happens if you go to mlab-ns directly?

mlab-ns.appspot.com/ndt

**Comment by georgiamoon** [comment]
First I got Chicago, then Toronto, then Madrid.

On Mon, Jun 22, 2015 at 1:57 PM, mtlynch notifications@github.com wrote:

> Is this an mlab-ns issue or a measure-app issue? What happens if you go to
> mlab-ns directly?
> 
> mlab-ns.appspot.com/ndt
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/m-lab/measure-app/issues/15#issuecomment-114199590.

## 

Georgia Bullen
Open Technology Institute http://newamerica.org/oti/ @ New America
http://newamerica.org
@georgiamoon http://twitter.com/georgiamoon

**Comment by mtlynch** [comment]
Closing as this is a mlab-ns issue, not a measure-app issue.

@georgiamoon - can you hit http://mlab-nstesting.appspot.com/ndt and let me know roughly what time and I'll check the logs for you to see what's going on?

**Comment by georgiamoon** [comment]
Yeah, this is from my home connection, so I'll check tonight. lmk where I
should put info

On Tue, Jun 23, 2015 at 10:12 AM, mtlynch notifications@github.com wrote:

> Closed #15 https://github.com/m-lab/measure-app/issues/15.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/m-lab/measure-app/issues/15#event-337864862.

## 

Georgia Bullen
Open Technology Institute http://newamerica.org/oti/ @ New America
http://newamerica.org
@georgiamoon http://twitter.com/georgiamoon

**Comment by mtlynch** [comment]
You can either email me or file a bug on https://github.com/m-lab/mlab-ns
