### ISSUE TITLE
When app runs constantly, does not show last result at all

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/measure-app#16]

**Comment by collina** [comment]
Ticket unclear, behavior works as expected for me.

**Comment by georgiamoon** [comment]
I'm not seeing it now, so i'll close this now.

**Comment by georgiamoon** [comment]
OK - Sorry - here's what I mean:
![screen shot 2015-06-30 at 12 00 12 am](https://cloud.githubusercontent.com/assets/941210/8423685/3fba7660-1ebb-11e5-98ea-e558864842ae.png)

If the app is set to run in the background, the most recent result doesn't show.

**Comment by collina** [comment]
The More button should lead to the result of the background test, and will not display the background result on the main screen. Correct?

**Comment by georgiamoon** [comment]
Yes, but why wouldn't we also show the result, like we do when a user clicks to run a test?

**Comment by georgiamoon** [comment]
View when I click to run:
![screen shot 2015-06-30 at 11 43 34 am](https://cloud.githubusercontent.com/assets/941210/8435069/48e60e0e-1f1d-11e5-987a-0c52b78eb14b.png)

**Comment by georgiamoon** [comment]
Unrelated, but I ran that one just now from the office, so not sure why the ISP didn't update?

**Comment by collina** [comment]
Fair point on background feedback, pushed an update to provide at least some.

**Comment by collina** [comment]
Opened ticket #33 for that ISP update, short answer is to do so I need to continually ping an external service. Currently this is a third party application, but we should stand up our own on GAE.

**Comment by georgiamoon** [comment]
Sounds good.

On Tue, Jun 30, 2015 at 12:11 PM, Collin Anderson notifications@github.com
wrote:

> Closed #16 https://github.com/m-lab/measure-app/issues/16.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/m-lab/measure-app/issues/16#event-344400631.

## 

Georgia Bullen
Open Technology Institute http://newamerica.org/oti/ @ New America
http://newamerica.org
@georgiamoon http://twitter.com/georgiamoon
