### ISSUE TITLE
Make the Privacy Policy a little easier to read

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/measure-app#20]
- maybe with section headers of some kind

I can take a look at this this week, or really just some spacing and headers.. otherwise no one will read it.

**Comment by collina** [comment]
It's filler text, which I have asked for help on several times.

**Comment by georgiamoon** [comment]
I only saw one request (and didn't know you had made the wiki page), but I just made some edits on the wiki page: https://github.com/m-lab/measure-app/wiki/Privacy-Policy
