### ISSUE TITLE
No timestamp on test history

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/measure-app#29]
When I look to see what time my test ran in the history on the applcation, there's no time in the Time line, just a date.

![screen shot 2015-06-22 at 5 50 19 pm](https://cloud.githubusercontent.com/assets/941210/8294010/2ce75922-1907-11e5-9c24-4e84e3843c57.png)

**Comment by collina** [comment]
Done, didn't think I had space but it should fit.
