### ISSUE TITLE
Need a status indicator somewhere on the computer that Measure is running

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/measure-app#32]
I've noticed that when Measure does run in the background, my browser will hang for a moment, so I should say that that's what it seems like. Ideally I'd be able to know through some sort of notification that the application is running, and then I'd know for sure and not just have a feeling of wanting to blame the app.

**Comment by georgiamoon** [comment]
@gembarrett -- play with status icons to give more subtle feedback that the app is running.

**Comment by georgiamoon** [comment]
@georgiamoon -- suggested chrome notifications, @cda and @gembarrett decided let's hold on that for now until we get user feedback otherwise.

**Comment by critzo** [comment]
@sajacy @collina have addressed this issue. color indicators on the App icon show when a test is running (purple) and when a test has been completed (blue)
