### ISSUE TITLE
Changes to location of some menu items, add page for bandwidth consumption text

### ISSUE THREAD

**Issue by critzo** [m-lab/measure-app#35]
- Move "Data Consumed" from Settings to a top level menu item, and make the menu item a link to a new page about bandwidth consumption (text TBD)
- Move "About", "Get Involved" and "Privacy Policy" from Settings to the top level menu

**Comment by georgiamoon** [comment]
Related to #22, 

After 10/6/15 meeting with SimplySecure (and from my notes), here are my proposed menus:

Top Level:
- Measure (or "Test/Measure my Internet")
  - Data Usage -- X.X Mbps (!) --> #18, #46
  - Settings
    - Location #47
    - Schedule a Test
    - TBD
  - History (or "Explore Data")
- About
  - Privacy Policy #20, 
  - Get Involved
    - Contribute data
    - Translate the application
    - Share data
    - TBD
