### ISSUE TITLE
create appengine service site to provide clients with ISP info

### ISSUE THREAD

**Issue by critzo** [m-lab/measure-app#43]

**Comment by critzo** [comment]
Just adding a quick note to this thread. At the Sept. retreat, Ya and I were discussing her current work, which is apparently building a databases by IP address over time. She said the goal was to eventually reprocess all data to include ISP information. @yachang @stephenstuart is this duplicative of the service described in this issue? Is it planned that the code Ya is producing will be available open source? @cda @georgiamoon just wanted to flag this for you that while @cda is likely building this as a separate service in the short term, @yachang 's work here might be a longer term contribution to help produce this general data service.

**Comment by georgiamoon** [comment]
@cda has a dev service up and running. it's in use.

For after 10/13/15, questions:
- stability of the service
- cost to stand it up
- maintenance

**Comment by georgiamoon** [comment]
http://measure-location.appspot.com/
