### ISSUE TITLE
Create instructions for building and running the extension

### ISSUE THREAD

**Issue by gembarrett** [m-lab/measure-app#44]
Imperative to help future devs work on this. Need full instructions on how to run the extension in browser (locally for development). Following are some of the steps I've picked up after check out, but there's additional steps to be written (e.g. to allow access to scheduled testing options in Settings):
- install [Node](https://nodejs.org/en/)
- install [Cordova/Ionic](http://ionicframework.com/) `npm install -g cordova ionic`
- `git clone https://github.com/m-lab/measure-app.git`
- `cd measure-app`
- `npm install` (may require sudo)
- `cordova platform add browser`
- `ionic build browser`
- `cd platforms/browser/build`
- `unzip package.zip`
- Open Chrome
- Window > Extensions
- ensure Developer Mode is checked
- Load unpacked extension
- navigate to local copy of measure-app/platforms/browser/build
- hit Select
- extension should now be enabled and visible in list of your Chrome extensions

**Comment by critzo** [comment]
resolved with the current read me.
