### ISSUE TITLE
Change Call To Action text

### ISSUE THREAD

**Issue by gembarrett** [m-lab/measure-app#45]
I'd like to suggest that "Tap to start" isn't quite right as a Call To Action on a non-mobile application. Can we look at alternatives please?

**Comment by georgiamoon** [comment]
Note from convo with SimplySecure -- Combine the feedback text with the Play button in the app so that there's only one place to call to action and click.

**Comment by critzo** [comment]
Changing the text to "Start Test" addresses this issue. I'll open a new issue for the next release to integrate the feedback text with the play button.
