### ISSUE TITLE
Add a warning about the data Consumed by the applcation

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/measure-app#46]
Need to provide explanation of why/how data is consumed by the application, and notification/warning that data is consumed when running

**Comment by critzo** [comment]
Amount of data used overall is displayed in the main menu. Perhaps we need a page or dialog when the data usage item is clicked to provide more info. Thoughts @georgiamoon ?

**Comment by georgiamoon** [comment]
Sure -- that would be a good way to handle that.

On Thu, Oct 29, 2015 at 11:45 AM, critzo notifications@github.com wrote:

> Amount of data used overall is displayed in the main menu. Perhaps we need
> a page or dialog when the data usage item is clicked to provide more info.
> Thoughts @georgiamoon https://github.com/georgiamoon ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/m-lab/measure-app/issues/46#issuecomment-152220714.

## 

Georgia Bullen
Open Technology Institute http://newamerica.org/oti/ @ New America
http://newamerica.org
@georgiamoon http://twitter.com/georgiamoon

*Note: *Our address is changing on November 2nd:
740 15th Street NW, Suite 900, Washington DC, 20005

**Comment by critzo** [comment]
Addressed in https://github.com/m-lab/measure-app/commit/e6881a86124d1b8f8ab7ff9f3a903bdfeffafe3a
