### ISSUE TITLE
choosing a server/location does not work

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/measure-app#70]
The UI shows the chosen location, but the test still runs against the closest server

Confirmed on the Chrome Extension & the Android port

**Comment by critzo** [comment]
Additionally, once an alternate location is selected, there's no apparent way to change back to the default, automatic location selection. This is a need for LIRNE Asia.

**Comment by georgiamoon** [comment]
Yes, @critzo that's issue #71

**Comment by critzo** [comment]
Ah sorry @georgiamoon should have looked closer.
