### ISSUE TITLE
Un-selecting a server doesn't seem to work

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/measure-app#71]
Selecting a server is working as of the recent commits to #66, but it's unclear how to unselect a server. You can't uncheck a server to go back to the app selecting the closest server

Not crucial at the moment, but eventually would be good to fix.

**Comment by sajacy** [comment]
There is currently no default or option for "automatic" in the UI but that can be exposed. (The logic exists to support that feature)

**Comment by georgiamoon** [comment]
That'd be ideal, and maybe the way to approach this is more what @cda
discussed where there's a settings file where we can limit the servers that
show in the list -- e.g. to do a limited release focused on a given area or
region. if that's feasible.

Regardless I think we want "automatic" to show as an option we can return
to.
