### ISSUE TITLE
'gulp extension' not working properly

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/measure-app#73]
I'm not getting the browser extension added into 'platforms', even though 'gulp extension' seems to work properly.

**Comment by sajacy** [comment]
Oh - it won't create a platform subdir. It just swaps the manifest so you can just add the www folder as an unpacked extension.

**Comment by georgiamoon** [comment]
OH! So then it's just a docs problem. The readme refers to
'platform/browser/www'
